In [1]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

"""
suppose you want to predict the likelihood that a particular user will purchase a product based on their 
past purchases and their interactions with other users in a social network. In this case, you could 
represent the social network as a graph, with users as nodes and interactions as edges, and use a GCN to make predictions.

"""
# define the GCN model
class GCN(torch.nn.Module):
    def __init__(self):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(16, 16)
        self.conv2 = GCNConv(16, 2)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

# create a sample graph
x = torch.randn(4, 16)
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)

"""
In the GCN example, x represents the input feature matrix of the graph. 
Each row of x represents the features of a single node in the graph, and the columns represent the 
different feature dimensions.

For example, if you have a social network graph where each node represents a user, the feature matrix x 
could contain information about each user such as their age, gender, occupation, etc.
In this case, the first row of edge_index represents the indices of the starting nodes of the edges, 
and the second row represents the indices of the ending nodes of the edges.
"""
# create a sample label vector
y = torch.tensor([0, 1, 0, 1], dtype=torch.long)


/Users/joonghochoi/miniconda3/envs/sweAI/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x

tensor([[ 1.5148e+00,  8.3878e-01,  2.1134e-01, -2.2476e+00,  7.2010e-01,
          1.3814e+00,  9.6319e-01, -1.2995e-01, -1.3041e+00,  2.7482e-01,
          1.2426e+00, -1.3262e+00,  1.6664e+00,  1.7723e+00,  8.8828e-01,
         -1.6411e+00],
        [ 3.6973e-01,  8.0648e-01, -5.4468e-01,  9.6007e-01,  1.1127e+00,
          3.8415e-01,  1.2402e+00, -3.5073e-01,  1.3398e+00, -8.9889e-01,
         -1.9971e+00, -1.6970e+00, -3.1169e-01,  2.3415e+00,  4.9778e-02,
          1.6866e+00],
        [ 1.1090e+00,  7.1571e-01, -4.5003e-01, -3.8010e-01,  7.4079e-01,
         -2.0750e+00,  4.6207e-01, -2.1992e-01, -3.1712e+00,  1.2053e+00,
         -4.7447e-01, -1.2831e+00,  1.2095e+00,  1.0795e-01,  2.1338e+00,
          1.4114e+00],
        [ 6.1188e-01, -5.3567e-01,  1.0024e-01, -5.3539e-01,  9.9342e-01,
          2.2453e-01, -7.2179e-01,  9.2756e-01, -1.1926e-03,  1.7966e+00,
          5.6617e-01, -1.3462e+00, -1.2057e+00,  1.1720e+00,  4.6209e-01,
          9.4006e-02]])

In [3]:
edge_index

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [6]:

# initialize the GCN model
model = GCN()

# define the optimizer and loss function
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.NLLLoss() # negative log likelihood loss.

# train the model
for epoch in range(500):
    model.train()
    optimizer.zero_grad()
    out = model(x, edge_index)
    loss = criterion(out, y)
    loss.backward()
    optimizer.step()

# test the model
model.eval()
out = model(x, edge_index)
pred = out.max(dim=1)[1]

In [7]:
pred

tensor([0, 1, 0, 1])